# Generated by Django 6.0.2 on 2026-02-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_portfoliopage_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopage',
            name='cv_url',
            field=models.URLField(blank=True),
        ),
    ]
